QBShared = QBShared or {}
QBShared.ForceJobDefaultDutyAtLogin = false -- true: Force duty state to jobdefaultDuty | false: set duty state from database last saved
QBShared.Jobs = {
	unemployed = { label = 'Civil', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Freelancer', payment = 10 } } },
	bus = { label = 'Autobús', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Conductor', payment = 50 } } },
	judge = { label = 'Honorario', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Juez', payment = 100 } } },
	lawyer = { label = 'Bufete', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Asociado', payment = 50 } } },
	-- reporter = { label = 'Reportero', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Periodista', payment = 50 } } },
	trucker = { label = 'Camionero', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Conductor', payment = 50 } } },
	tow = { label = 'Grua', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Conductor', payment = 50 } } },
	garbage = { label = 'Basura', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Recolector', payment = 50 } } },
	vineyard = { label = 'Viñedo', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Recolector', payment = 50 } } },
	hotdog = { label = 'Puesto de Hotdog', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Vendedor', payment = 50 } } },

	police = {
		label = 'Police',
		type = 'leo',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recluta', payment = 25 },
			['1'] = { name = 'Patrullero', payment = 40 },
			['2'] = { name = 'Oficial', payment = 70 },
			['3'] = { name = 'Teniente', payment = 90 },
			['4'] = { name = 'Coronel', payment = 150 },
			['5'] = { name = 'General', isboss = true, payment = 200 },
		},
	},
	ambulance = {
		label = 'EMS',
		type = 'ems',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Paramedico', payment = 25 },
			['1'] = { name = 'Enfermero', payment = 40 },
			['2'] = { name = 'Enfermero Jefe', payment = 70 },
			['3'] = { name = 'Médico', payment = 90 },
			['4'] = { name = 'Especialista', payment = 150 },
			['5'] = { name = 'Director General', isboss = true, payment = 200 },
		},
	},
	realestate = {
		label = 'Real Estate',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 25 },
			['1'] = { name = 'House Sales', payment = 40 },
			['2'] = { name = 'Business Sales', payment = 70 },
			['3'] = { name = 'Broker', payment = 1000 }, -- Considerando comisiones más altas
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
	taxi = {
		label = 'Taxi',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 20 },
			['1'] = { name = 'Driver', payment = 30 },
			['2'] = { name = 'Event Driver', payment = 60 },
			['3'] = { name = 'Sales', payment = 80 },
			['4'] = { name = 'Manager', isboss = true, payment = 120 },
		},
	},
	cardealer = {
		label = 'Vehicle Dealer',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 25 },
			['1'] = { name = 'Showroom Sales', payment = 40 },
			['2'] = { name = 'Business Sales', payment = 70 },
			['3'] = { name = 'Finance', payment = 90 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
	mechanic = {
		label = 'LS Customs',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Mecánico aprendiz', payment = 20 },
			['1'] = { name = 'Mecánico', payment = 35 },
			['2'] = { name = 'Jefe de taller', payment = 60 },
			['3'] = { name = 'Jefe Mecánico', isboss = true, payment = 120 },
		},
	},	
	mechanic2 = {
		label = 'LS Customs',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recluta', payment = 25 },
			['1'] = { name = 'Novato', payment = 35 },
			['2'] = { name = 'Experimentado', payment = 60 },
			['3'] = { name = 'Avanzado', payment = 80 },
			['4'] = { name = 'Gerente', isboss = true, payment = 130 },
		},
	},
	
	mechanic3 = {
		label = 'LS Customs',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recluta', payment = 25 },
			['1'] = { name = 'Novato', payment = 35 },
			['2'] = { name = 'Experimentado', payment = 60 },
			['3'] = { name = 'Avanzado', payment = 80 },
			['4'] = { name = 'Gerente', isboss = true, payment = 130 },
		},
	},
	
	beeker = {
		label = 'Beeker\'s Garage',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recluta', payment = 25 },
			['1'] = { name = 'Novato', payment = 35 },
			['2'] = { name = 'Experimentado', payment = 60 },
			['3'] = { name = 'Avanzado', payment = 80 },
			['4'] = { name = 'Gerente', isboss = true, payment = 130 },
		},
	},
	bennys = {
		label = 'Benny\'s Original Motor Works',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recluta', payment = 25 },
			['1'] = { name = 'Novato', payment = 35 },
			['2'] = { name = 'Experimentado', payment = 60 },
			['3'] = { name = 'Avanzado', payment = 80 },
			['4'] = { name = 'Gerente', isboss = true, payment = 130 },
		},
	},
	vunicorn = {
		label = 'Vanilla Unicorn',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Aprendiz', payment = 25 },
			['1'] = { name = 'Empleado', payment = 35 },
			['2'] = { name = 'Bar Staff', payment = 45 },
			['3'] = { name = 'Bailarín', payment = 55 },
			['4'] = { name = 'Gerente', isboss = true, payment = 80 },
			['5'] = { name = 'Dueño', isboss = true, payment = 150 },
		},
	},
	uwu = {
		label = 'UwU Cat Cafe',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Novato', payment = 25 },
			['1'] = { name = 'Empleado', payment = 35 },
			['2'] = { name = 'Experimentado', payment = 60 },
			['3'] = { name = 'Avanzado', payment = 80 },
			['4'] = { name = 'Jefe', isboss = true, payment = 130 },
		},
	},	
}
