Config = Config or {}

Config.UsingPsHousing = false
Config.UsingDefaultQBApartments = true
Config.OnlyShowOnDuty = true
Config.UseCQCMugshot = true

-- Front, Back Side. Use 4 for both sides, we recommend leaving at 1 for default.
Config.MugPhotos = 1

-- If set to true = Fine gets automatically removed from bank automatically charging the player.
-- If set to false = The fine gets sent as an Invoice to their phone and it us to the player to pay for it, can remain unpaid and ignored.
Config.BillVariation = true

-- If set to false (default) = The fine amount is just being removed from the player's bank account
-- If set to true = The fine amount is beeing added to the society account after being removed from the player's bank account
Config.QBBankingUse = false

-- Set up your inventory to automatically retrieve images when a weapon is registered at a weapon shop or self-registered.
-- If you're utilizing lj-inventory's latest version from GitHub, no further modifications are necessary. 
-- However, if you're using a different inventory system, please refer to the "Inventory Edit | Automatic Add Weapons with images" section in ps-mdt's README.
Config.InventoryForWeaponsImages = "qb-inventory"

-- "LegacyFuel", "lj-fuel", "ps-fuel"
Config.Fuel = "LegacyFuel"

-- Google Docs Link
Config.sopLink = {
    ['police'] = '',
    ['ambulance'] = '',
    ['bcso'] = '',
    ['doj'] = '',
    ['sast'] = '',
    ['sasp'] = '',
    ['doc'] = '',
    ['lssd'] = '',
    ['sapr'] = '',
}

-- Google Docs Link
Config.RosterLink = {
    ['police'] = '',
    ['ambulance'] = '',
    ['bcso'] = '',
    ['doj'] = '',
    ['sast'] = '',
    ['sasp'] = '',
    ['doc'] = '',
    ['lssd'] = '',
    ['sapr'] = '',	
}

Config.PoliceJobs = {
    ['police'] = true,
    ['lspd'] = true,
    ['bcso'] = true,
    ['sast'] = true,
    ['sasp'] = true,
    ['doc'] = true,
    ['lssd'] = true,
    ['sapr'] = true,
    ['pa'] = true
}

Config.AmbulanceJobs = {
    ['ambulance'] = true,
    ['doctor'] = true
}

Config.DojJobs = {
    ['lawyer'] = true,
    ['judge'] = true
}

-- This is a workaround solution because the qb-menu present in qb-policejob fills in an impound location and sends it to the event. 
-- If the impound locations are modified in qb-policejob, the changes must also be implemented here to ensure consistency.

Config.ImpoundLocations = {
    [1] = vector4(436.68, -1007.42, 27.32, 180.0),
    [2] = vector4(-436.14, 5982.63, 31.34, 136.0),
}

-- Support for Wraith ARS 2X. 

Config.UseWolfknightRadar = false
Config.WolfknightNotifyTime = 5000 -- How long the notification displays for in milliseconds (30000 = 30 seconds)
Config.PlateScanForDriversLicense = false -- If true, plate scanner will check if the owner of the scanned vehicle has a drivers license

-- IMPORTANT: To avoid making excessive database queries, modify this config to true 'CONFIG.use_sonorancad = true' setting in the configuration file located at 'wk_wars2x/config.lua'. 
-- Enabling this setting will limit plate checks to only those vehicles that have been used by a player.

Config.LogPerms = {
	['ambulance'] = {
		[4] = true,
	},
	['police'] = {
		[4] = true,
	},
    ['bcso'] = {
		[4] = true,
	},
    ['sast'] = {
		[4] = true,
	},
    ['sasp'] = {
		[4] = true,
	},
    ['sapr'] = {
		[4] = true,
	},
    ['doc'] = {
		[4] = true,
	},
    ['lssd'] = {
		[4] = true,
	},
}

Config.RemoveIncidentPerms = {
	['ambulance'] = {
		[4] = true,
	},
	['police'] = {
		[4] = true,
	},
    ['bcso'] = {
		[4] = true,
	},
    ['sast'] = {
		[4] = true,
	},
    ['sasp'] = {
		[4] = true,
	},
    ['sapr'] = {
		[4] = true,
	},
    ['doc'] = {
		[4] = true,
	},
    ['lssd'] = {
		[4] = true,
	},
}

Config.RemoveReportPerms = {
	['ambulance'] = {
		[4] = true,
	},
	['police'] = {
		[4] = true,
	},
    ['bcso'] = {
		[4] = true,
	},
    ['sast'] = {
		[4] = true,
	},
    ['sasp'] = {
		[4] = true,
	},
    ['sapr'] = {
		[4] = true,
	},
    ['doc'] = {
		[4] = true,
	},
    ['lssd'] = {
		[4] = true,
	},
}

Config.RemoveWeaponsPerms = {
	['ambulance'] = {
		[4] = true,
	},
	['police'] = {
		[4] = true,
	},
    ['bcso'] = {
		[4] = true,
	},
    ['sast'] = {
		[4] = true,
	},
    ['sasp'] = {
		[4] = true,
	},
    ['sapr'] = {
		[4] = true,
	},
    ['doc'] = {
		[4] = true,
	},
    ['lssd'] = {
		[4] = true,
	},
}

Config.PenalCodeTitles = {
   [1] = 'DELACIONES CONTRA LAS PERSONAS',
   [2] = 'DELITOS QUE IMPLICAN ROBO',
   [3] = 'DELITOS QUE IMPLICAN FRAUDE',
   [4] = 'INFRACCIONES QUE IMPLICAN DAÑOS A LA PROPIEDAD',
   [5] = 'DALACIONES CONTRA LA ADMINISTRACIÓN PÚBLICA',
   [6] = 'INFRACCIONES CONTRA EL ORDEN PÚBLICO',
   [7] = 'OFENSAS CONTRA LA SALUD Y LA MORAL',
   [8] = 'FALTAS CONTRA LA SEGURIDAD PÚBLICA',
   [9] = 'INFRACCIONES QUE IMPLICAN LA OPERACIÓN DE UN VEHÍCULO',
   [10] = 'DELITOS QUE IMPLICAN EL BIENESTAR DE LA VIDA SILVESTRE',
}

Config.PenalCode = {
    [1] = {
        [1] = {title = 'Asalto simple', class = 'Misdemeanor', id = 'P.C. 1001', months = 7, fine = 500, color = 'green', description = 'Cuando una persona intencionalmente o a sabiendas causa contacto físico con otra (sin arma)'},
        [2] = {title = 'Agresión', class = 'Misdemeanor', id = 'P.C. 1002', months = 15, fine = 850, color = 'orange', description = 'Si una persona intencionalmente o con conocimiento causa daño a otra (sin arma)'},
        [3] = {title = 'Asalto agravado', class = 'Felony', id = 'P.C. 1003', months = 20, fine = 1250, color = 'orange', description = 'Cuando una persona, sin intención e imprudencia, causa lesiones corporales a otra como resultado de una confrontación Y causa lesiones corporales'},
        [4] = {title = 'Asalto con arma mortal', class = 'Felony', id = 'P.C. 1004', months = 30, fine = 3750, color = 'red', description = 'Cuando una persona intencionalmente, a sabiendas o imprudentemente causa lesiones corporales a otra persona Y causa lesiones corporales graves o usa o exhibe un arma mortal'},
        [5] = {title = 'Homicidio involuntario', class = 'Felony', id = 'P.C. 1005', months = 60, fine = 7500, color = 'red', description = 'Cuando una persona causa involuntariamente y por imprudencia la muerte de otra'},
        [6] = {title = 'Homicidio vehicular', class = 'Felony', id = 'P.C. 1006', months = 75, fine = 7500, color = 'red', description = 'Cuando una persona causa involuntariamente y por imprudencia la muerte de otra con un vehículo'},
        [7] = {title = 'Intento de asesinato de un civil', class = 'Felony', id = 'P.C. 1007', months = 50, fine = 7500, color = 'red', description = 'Cuando una persona no gubernamental ataca intencionalmente a otra con la intención de matarla.'},
        [8] = {title = 'Asesinato en segundo grado', class = 'Felony', id = 'P.C. 1008', months = 100, fine = 15000, color = 'red', description = 'Cualquier asesinato intencional que no sea premeditado o planeado. Una situación en la que el asesino sólo pretende infligir daños corporales graves.'},
        [9] = {title = 'Complice de asesinato en segundo grado', class = 'Felony', id = 'P.C. 1009', months = 50, fine = 5000, color = 'red', description = 'Estar presente y/o participar en el acto de cargo de los implicados.'},
        [10] = {title = 'Asesinato en primer grado', class = 'Felony', id = 'P.C. 1010', months = 0, fine = 0, color = 'red', description = 'Cualquier homicidio intencional y premeditado con malicia.'},
        [11] = {title = 'Complice de asesinato en primer grado', class = 'Felony', id = 'P.C. 1011', months = 0, fine = 0, color = 'red', description = 'Estar presente y/o participar en el acto de cargo de los implicados'},
        [12] = {title = 'Asesinato de un servidor público o agente del orden público', class = 'Felony', id = 'P.C. 1012', months = 0, fine = 0, color = 'red', description = 'Cualquier asesinato intencional cometido contra un empleado del gobierno.'},
        [13] = {title = 'Intento de asesinato de un servidor público o agente del orden público', class = 'Felony', id = 'P.C. 1013', months = 65, fine = 10000, color = 'red', description = 'Cualquier ataque que se realice a un empleado del gobierno con la intención de causarle la muerte.'},
        [14] = {title = 'Complice del asesinato de un servidor público o agente del orden público', class = 'Felony', id = 'P.C. 1014', months = 0, fine = 0, color = 'red', description = 'Estar presente y/o participar en el acto de cargo de los implicados.'},
        [15] = {title = 'Secuestro prolongado', class = 'Misdemeanor', id = 'P.C. 1015', months = 10, fine = 600, color = 'green', description = 'El acto de tomar a otra persona en contra de su voluntad y retenerla por un período prolongado de tiempo.'},
        [16] = {title = 'Secuestro', class = 'Felony', id = 'P.C. 1016', months = 15, fine = 900, color = 'orange', description = 'El acto de tomar a otro en contra de su voluntad por un corto período de tiempo.'},
        [17] = {title = 'cómplice del secuestro', class = 'Felony', id = 'P.C. 1017', months = 7, fine = 450, color = 'orange', description = 'Estar presente y/o participar en el acto'},
        [18] = {title = 'Intento de secuestro', class = 'Felony', id = 'P.C. 1018', months = 10, fine = 450, color = 'orange', description = 'El acto de intentar llevarse a alguien en contra de su voluntad.'},
        [19] = {title = 'Toma de rehenes', class = 'Felony', id = 'P.C. 1019', months = 20, fine = 1200, color = 'orange', description = 'El acto de tomar a otro en contra de su voluntad para beneficio personal.'},
        [20] = {title = 'cómplice de la toma de rehenes', class = 'Felony', id = 'P.C. 1020', months = 10, fine = 600, color = 'orange', description = 'Estar presente y/o participar en el acto'},
        [21] = {title = 'Secuestro prolongado de un servidor público o agente del orden público.', class = 'Felony', id = 'P.C. 1021', months = 25, fine = 4000, color = 'orange', description = 'El acto de tomar a un empleado del gobierno contra su voluntad por un período prolongado.'},
        [22] = {title = 'Amenazas criminales', class = 'Misdemeanor', id = 'P.C. 1022', months = 5, fine = 500, color = 'orange', description = 'El acto de manifestar la intención de cometer un delito contra otro.'},
        [23] = {title = 'Imprudencia temeraria', class = 'Misdemeanor', id = 'P.C. 1023', months = 10, fine = 1000, color = 'orange', description = 'El acto de ignorar la seguridad de otra persona que puede poner a otra en peligro de muerte o lesiones corporales.'},
        [24] = {title = 'Tiroteo relacionado con pandillas', class = 'Felony', id = 'P.C. 1024', months = 30, fine = 2500, color = 'red', description = 'El acto en el que se dispara un arma de fuego en relación con la actividad de pandillas.'},
        [25] = {title = 'Canibalismo', class = 'Felony', id = 'P.C. 1025', months = 0, fine = 0, color = 'red', description = 'El acto en el que una persona consume voluntariamente la carne de otra.'},
        [26] = {title = 'Tortura', class = 'Felony', id = 'P.C. 1026', months = 40, fine = 4500, color = 'red', description = 'El acto de causar daño a otro para extraer información o para el disfrute personal.'},
    },
    [2] = {
        [1] = {title = 'Hurto A', class = 'Infraction', id = 'P.C. 2001', months = 0, fine = 250, color = 'green', description = 'El robo de propiedad por debajo de $50'},
        [2] = {title = 'Hurto B', class = 'Misdemeanor', id = 'P.C. 2002', months = 10, fine = 600, color = 'green', description = 'Robo de propiedad arriba $700'},
        [3] = {title = 'Hurto de Auto A', class = 'Felony', id = 'P.C. 2003', months = 15, fine = 900, color = 'green', description = 'El acto de robar un vehículo que pertenece a otra persona sin permiso.'},
        [4] = {title = 'Hurto de Auto B', class = 'Felony', id = 'P.C. 2004', months = 35, fine = 3500, color = 'green', description = 'El acto de robar un vehículo que pertenece a otra persona sin permiso y estando armado.'},
        [5] = {title = 'robo de auto', class = 'Felony', id = 'P.C. 2005', months = 30, fine = 2000, color = 'orange', description = 'El acto de alguien que quita por la fuerza un vehículo a sus ocupantes.'},
        [6] = {title = 'Robo', class = 'Misdemeanor', id = 'P.C. 2006', months = 10, fine = 500, color = 'green', description = 'El acto de entrar ilegalmente en un edificio con la intención de cometer un delito, especialmente robo.'},
        [7] = {title = 'Robo de propiedad', class = 'Felony', id = 'P.C. 2007', months = 25, fine = 2000, color = 'green', description = 'La acción de tomar propiedad ilegalmente de una persona o lugar por la fuerza o amenaza de fuerza.'},
        [8] = {title = 'cómplice del robo', class = 'Felony', id = 'P.C. 2008', months = 12, fine = 1000, color = 'green', description = 'Estar presente y/o participar en el acto.'},
        [9] = {title = 'Intento de robo', class = 'Felony', id = 'P.C. 2009', months = 20, fine = 1000, color = 'green', description = 'La acción de atentar contra la propiedad ilegalmente de una persona o lugar por la fuerza o amenaza de fuerza.'},
        [10] = {title = 'Robo a mano armada', class = 'Felony', id = 'P.C. 2010', months = 30, fine = 3000, color = 'orange', description = 'La acción de tomar propiedad ilegalmente de una persona o lugar por la fuerza o amenaza de fuerza estando armado.'},
        [11] = {title = 'Complice de robo a mano armada', class = 'Felony', id = 'P.C. 2011', months = 15, fine = 1500, color = 'orange', description = 'Estar presente y/o participar en el acto'},
        [12] = {title = 'Intento de robo a mano armada', class = 'Felony', id = 'P.C. 2012', months = 25, fine = 1500, color = 'orange', description = 'La acción de atentar contra la propiedad ilegalmente de una persona o lugar por la fuerza o amenaza de fuerza estando armado..'},
        [13] = {title = 'Hurto mayor', class = 'Felony', id = 'P.C. 2013', months = 45, fine = 7500, color = 'orange', description = 'Robo de propiedad personal que tenga un valor superior a una cantidad legalmente especificada.'},
        [14] = {title = 'Irse sin pagar', class = 'Infraction', id = 'P.C. 2014', months = 0, fine = 500, color = 'green', description = 'El acto de abandonar un establecimiento sin pagar el servicio prestado.'},
        [15] = {title = 'Posesión de moneda no legal', class = 'Misdemeanor', id = 'P.C. 2015', months = 10, fine = 750, color = 'green', description = 'Estar en posesión de moneda robada'},
        [16] = {title = 'Posesión de artículos emitidos por el gobierno', class = 'Misdemeanor', id = 'P.C. 2016', months = 15, fine = 1000, color = 'green', description = 'Estar en posesión de artículos que sólo pueden adquirir los empleados del gobierno.'},
        [17] = {title = 'Posesión de artículos utilizados en la comisión de un delito', class = 'Misdemeanor', id = 'P.C. 2017', months = 10, fine = 500, color = 'green', description = 'Estar en posesión de artículos que se utilizaron anteriormente para cometer delitos.'},
        [18] = {title = 'Venta de artículos utilizados en la comisión de un delito', class = 'Felony', id = 'P.C. 2018', months = 15, fine = 1000, color = 'orange', description = 'El acto de vender artículos que anteriormente se utilizaron para cometer delitos.'},
        [19] = {title = 'Robo de una aeronave', class = 'Felony', id = 'P.C. 2019', months = 20, fine = 1000, color = 'green', description = 'El acto de robar un avión.'},
    },
    [3] = {
        [1] = {title = 'Suplantacion', class = 'Delito menor', id = 'P.C. 3001', months = 15, fine = 1250, color = 'green', description = 'La acción de identificarse falsamente como otra persona para engañar'},
        [2] = {title = 'Suplantar un oficial de paz o servidor público', class = 'Delito grave', id = 'P.C. 3002', months = 25, fine = 2750, color = 'green', description = 'La acción de identificarse falsamente como empleado del gobierno para engañar'},
        [3] = {title = 'Suplantar un juez', class = 'Delito grave', id = 'P.C. 3003', months =0, fine = 0, color='green', description = 'La acción de identificarse falsamente como Juez para engañar'},
        [4] = {title = 'Posesión de identificación robada', class = 'Delito menor', id = 'P.C. 3004', months = 10, fine = 750, color = 'green', description = 'Tener Identificación de otra persona sin consentimiento'},
        [5] = {title = 'Posesión de identificación gubernamental robada', class = 'Delito menor', id = 'P.C. 3005', months = 20, fine = 2000, color = 'green', description = 'Tener la identificación de un empleado del gobierno sin consentimiento'},
        [6] = {title = 'Extorsión', class = 'Delito grave', id = 'P.C. 3006', months = 20, fine = 900, color = 'orange', description = 'Amenazar o causar daño a una persona o propiedad para obtener ganancias financieras'},
        [7] = {title = 'Fraude', class = 'Delito menor', id = 'P.C. 3007', months = 10, fine = 450, color = 'green', description = 'Engañar a otro para obtener ganancias económicas'},
        [8] = {title = 'Falsificación', class = 'Delito menor', id = 'P.C. 3008', months = 15, fine = 750, color = 'green', description = 'Falsificar documentación legal para beneficio personal'},
        [9] = {title = 'Lavado de Dinero', class = 'Delito grave', id = 'P.C. 3009', months = 0, fine = 0, color = 'red', description = 'El procesamiento de dinero robado para moneda legal'},
    },
    [4] = {
        [1] = {title = 'Invasión', class = 'Delito menor', id = 'P.C. 4001', months = 10, fine = 450, color = 'green', description = 'Que una persona esté dentro de los límites de un lugar al cual no está legalmente permitido'},
        [2] = {title = 'Delito grave de invasión', class = 'Delito grave', id = 'P.C. 4002', months = 15, fine = 1500, color = 'green', description = 'Que una persona haya entrado repetidamente en los límites de un lugar en el que, a sabiendas, no está permitido legalmente'},
        [3] = {title = 'Incendio provocado', class = 'Delito grave', id = 'P.C. 4003', months = 15, fine = 1500, color = 'orange', description = 'El uso de fuego y acelerantes para destruir, dañar o causar la muerte maliciosamente a una persona o propiedad'},
        [4] = {title = 'Vandalismo', class = 'Infracción', id = 'P.C. 4004', months = 0, fine = 300, color='green', description = 'La destrucción intencionada de bienes'},
        [5] = {title = 'Vandalismo de propiedad gubernamental', class = 'Delito grave', id = 'P.C. 4005', months = 20, fine = 1500, color = 'green', description = 'La destrucción intencional de propiedad del gobierno'},
        [6] = {title = 'Tirar basura', class = 'Infracción', id = 'P.C. 4006', months = 0, fine = 200, color = 'green', description = 'El descarte intencional de basura en un contenedor abierto y no en el contenedor designado'},
    },
    [5] = {
        [1] = {title = 'Soborno de un funcionario gubernamental', class = 'Delito grave', id = 'P.C. 5001', months =  20, fine = 3500, color = 'green', description = 'el uso de dinero, favores o propiedades para ganarse el favor de un funcionario del gobierno'},
        [2] = {title = 'Ley Antienmascaramiento', class = 'Infracción', id = 'P.C. 5002', months =  0, fine = 750, color = 'green', description = 'Usar mascarilla en zona prohibida'},
        [3] = {title = 'Posesión de contrabando en una instalación gubernamental', class = 'Delito grave', id = 'P.C. 5003', months =  25, fine = 1000, color = 'green', description = 'Estar en posesión de artículos que son ilegales mientras se encuentre dentro de un edificio gubernamental'},
        [4] = {title = 'Posesión criminal de propiedad robada', class = 'Delito menor', id = 'P.C. 5004', months =  10, fine = 500, color = 'green', description = 'Estar en posesión de artículos robados con conocimiento o no'},
        [5] = {title = 'Escapar', class = 'Delito grave', id = 'P.C. 5005', months =  10, fine = 450, color = 'green', description = 'La acción de abandonar la custodia intencional y conscientemente mientras se está legalmente arrestado, detenido o en la cárcel'},
        [6] = {title = 'Fuga', class = 'Delito grave', id = 'P.C. 5006', months =  30, fine = 2500, color = 'orange', description = 'La acción de salir de la custodia estatal de un centro de detención estatal o del condado'},
        [7] = {title = 'Complice de fuga', class = 'Delito grave', id = 'P.C. 5007', months =  25, fine = 2000, color = 'orange', description = 'Estar presente y/o participar en el acto de carga parental'},
        [8] = {title = 'Intento de fuga', class = 'Delito grave', id = 'P.C. 5008', months =  20, fine = 1500, color = 'orange', description = 'El intento de fuga deliberado e intencional de un centro de detención estatal o del condado'},
        [9] = {title = 'Perjurio', class = 'Delito grave', id = 'P.C. 5009', months =  0, fine = 0, color = 'green', description = 'La acción de afirmar falsedades estando legalmente obligado a decir la verdad'},
        [10] = {title = 'Violación de una orden de restricción', class = 'Delito grave', id = 'P.C. 5010', months =  20, fine = 2250, color = 'green', description = 'La infracción intencionada y consciente de la documentación de protección ordenada por el tribunal'},
        [11] = {title = 'Malversación de fondos', class = 'Delito grave', id = 'P.C. 5011', months =  45, fine = 10000, color = 'green', description = 'El movimiento intencional y consciente de fondos de cuentas bancarias no personales a cuentas bancarias personales para beneficio personal'},
        [12] = {title = 'Práctica ilegal', class = 'Delito grave', id = 'P.C. 5012', months =  15, fine = 1500, color = 'orange', description = 'La acción de realizar un servicio sin la licencia y aprobación legal adecuada'},
        [13] = {title = 'Mal uso de los sistemas de emergencia', class = 'Infracción', id = 'P.C. 5013', months =  0, fine = 600, color = 'orange', description = 'Uso de equipo de emergencia gubernamental para fines no previstos'},
        [14] = {title = 'Conspiración', class = 'Delito menor', id = 'P.C. 5014', months =  10, fine = 450, color = 'green', description = 'El acto de planificar un delito pero aún no cometerlo'},
        [15] = {title = 'Violación de una orden judicial', class = 'Delito menor', id = 'P.C. 5015', months =  0, fine = 0, color = 'orange', description = 'La infracción de la documentación ordenada judicial'},
        [16] = {title = 'No comparecer', class = 'Delito menor', id = 'P.C. 5016', months =  0, fine = 0, color = 'orange', description = 'Cuando alguien que está legalmente obligado a comparecer ante el tribunal no lo hace'},
        [17] = {title = 'Desacato al tribunal', class = 'Delito grave', id = 'P.C. 5017', months =  0, fine = 0, color = 'orange', description = 'La interrupción del proceso judicial en una sala mientras se encuentra en sesión (decisión judicial)'},
        [18] = {title = 'Resistirse al arresto', class = 'Delito menor', id = 'P.C. 5018', months =  5, fine = 300, color = 'orange', description = 'El acto de no permitir que los agentes del orden público lo detengan voluntariamente'},
    },
    [6] = {
        [1] = {title = 'Desobedecer a un Oficial de Paz', class = 'infracción', id = 'P.C. 6001', months = 0, fine = 750, color = 'green', description = 'El desacato intencional de una orden legal'},
        [2] = {title = 'Conducta desordenada', class = 'Infracción', id = 'P.C. 6002', months = 0, fine = 250, color = 'green', description = 'Actuar de una manera que crea una condición peligrosa o físicamente ofensiva mediante cualquier acto que no sirva a ningún propósito legítimo del actor. '},
        [3] = {title = 'Perturbar la Paz', class = 'infracción', id = 'P.C. 6003', months = 0, fine = 350, color = 'green', description = 'Acción que causa disturbios y altera el orden público'},
        [4] = {title = 'Informes falsos', class = 'Delito menor', id = 'P.C. 6004', months = 10, fine = 750, color = 'green', description = 'El acto de denunciar un delito que no ocurrió'},
        [5] = {title = 'Acoso', class = 'Delito menor', id = 'P.C. 6005', months = 10, fine = 500, color = 'orange', description = 'La interrupción repetida o ataques verbales de otra persona'},
        [6] = {title = 'Delito menor de obstrucción de la justicia', class = 'Delito menor', id = 'P.C. 6006', months = 10, fine = 500, color = 'green', description = 'Actuar de manera que obstaculice el proceso de Justicia o investigaciones legales'},
        [7] = {title = 'Delito grave de obstrucción de la justicia', class = 'Delito grave', id = 'P.C. 6007', months = 15, fine = 900, color = 'green', description = 'Actuar de manera que obstaculice el proceso de Justicia o investigaciones legales usando la violencia'},
        [8] = {title = 'Incitar a un motín', class = 'Delito grave', id = 'P.C. 6008', months = 25, fine = 1000, color = 'orange', description = 'Causar disturbios civiles de manera que incite a un grupo a causar daño a personas o propiedades'},
        [9] = {title = 'Merodear en propiedades gubernamentales', class = 'Infracción', id = 'P.C. 6009', months = 0, fine = 500, color = 'green', description = 'Cuando alguien está presente en un gobierno propiamente dicho por un período prolongado de tiempo'},
        [10] = {title = 'Manipulación', class = 'Delito menor', id = 'P.C. 6010', months = 10, fine = 500, color = 'green', description = 'Cuando alguien intencional, consciente e indirectamente interfiere con puntos clave de una investigación legal'},
        [11] = {title = 'Manipulación de vehículos', class = 'Delito menor', id = 'P.C. 6011', months = 15, fine = 750, color = 'green', description = 'La interferencia deliberada y consciente del funcionamiento normal de un vehículo'},
        [12] = {title = 'Alteración de pruebas', class = 'Delito grave', id = 'P.C. 6012', months = 20, fine = 1000, color = 'green', description = 'La interferencia deliberada y consciente con pruebas de una investigación legal'},
        [13] = {title = 'Manipulación de testigos', class = 'Delito grave', id = 'P.C. 6013', months = 0, fine = 0, color = 'green', description = 'El entrenamiento o coacción deliberado y consciente de un testigo en una investigación legal'},
        [14] = {title = 'No proporcionar identificación', class = 'Delito menor', id = 'P.C. 6014', months = 15, fine = 1500, color = 'green', description = 'El acto de no presentar identificación cuando legalmente se le exige'},
        [15] = {title = 'Vigilantismo', class = 'Delito grave', id = 'P.C. 6015', months = 30, fine = 1500, color = 'orange', description = 'El acto de dedicarse a hacer cumplir la ley con autoridad legal para hacerlo'},
        [16] = {title = 'Reunión ilegal', class = 'Delito menor', id = 'P.C. 6016', months = 10, fine = 750, color = 'orange', description = 'cuando un grupo grande se reúne en un lugar que requiere aprobación previa para hacerlo'},
        [17] = {title = 'Corrupción gubernamental', class = 'Delito grave', id = 'P.C. 6017', months = 0, fine = 0, color = 'red', description = 'El acto de usar la posición política y el poder para beneficio propio'},
        [18] = {title = 'Acoso', class = 'Delito grave', id = 'P.C. 6018', months = 40, fine = 1500, color = 'orange', description = 'Cuando una persona monitorea a otra sin su consentimiento'},
        [19] = {title = 'Ayuda e incitación', class = 'Delito menor', id = 'P.C. 6019', months = 15, fine = 450, color = 'orange', description = 'Ayudar a alguien a cometer o animar a alguien a cometer un delito'},
        [20] = {title = 'Albergar a un fugitivo', class = 'Delito menor', id = 'P.C. 6020', months = 10, fine = 1000, color = 'green', description = 'Cuando alguien esconde voluntariamente a otro que es buscado por las autoridades'},
    },
    [7] = {
        [1] = {title = 'Posesión de marihuana', class = 'Delito menor', id = 'P.C. 7001', months = 5, fine = 250, color = 'green', description = 'La posesión de una cantidad de marihuana en la cantidad menor de los 4 porros'},
        [2] = {title = 'fabricación de marihuana', class = 'Delito grave', id = 'P.C. 7002', months = 15, fine = 1000, color = 'red', description = 'La posesión de una cantidad de marihuana que sea de fabricación'},
        [3] = {title = 'Cultivo de Marihuana A', class = 'Delito menor', id = 'P.C. 7003', months = 10, fine = 750, color = 'green', description = 'La posesión de 4 o menos plantas de marihuana'},
        [4] = {title = 'Cultivo de marihuana B', class = 'Delito grave', id = 'P.C. 7004', months = 30, fine = 1500, color = 'orange', description = 'La posesión de 5 o más plantas de marihuana'},
        [5] = {title = 'Posesión de marihuana con intención de distribuir', class = 'Delito grave', id = 'P.C. 7005', months = 30, fine = 3000, color = 'orange', description = 'La posesión de una cantidad de marihuana para su distribución'},
        [6] = {title = 'posesión de cocaína', class = 'Delito menor', id = 'P.C. 7006', months = 7, fine = 500, color = 'green', description = 'La posesión de cocaína en pequeñas cantidades generalmente para uso personal'},
        [7] = {title = 'fabricación y posesión de cocaína', class = 'Delito grave', id = 'P.C. 7007', months = 25, fine = 1500, color = 'red', description = 'La posesión de una cantidad de cocaína que sea de fabricación'},
        [8] = {title = 'Posesión de cocaína con intención de distribuir', class = 'Delito grave', id = 'P.C. 7008', months = 35, fine = 4500, color = 'orange', description = 'La posesión de una cantidad de Cocaína para su distribución'},
        [9] = {title = 'posesión de metanfetamina', class = 'Delito menor', id = 'P.C. 7009', months = 7, fine = 500, color = 'green', description = 'La posesión de metanfetamina en pequeñas cantidades generalmente para uso personal'},
        [10] = {title = 'fabricación y posesión de metanfetamina', class = 'Delito grave', id = 'P.C. 7010', months = 25, fine = 1500, color = 'red', description = 'La posesión de una cantidad de metanfetamina que sea de fabricación'},
        [11] = {title = 'Posesión de metanfetamina con intención de distribuir', class = 'Delito grave', id = 'P.C. 7011', months = 35, fine = 4500, color = 'orange', description = 'La posesión de una cantidad de Metanfetamina para su distribución'},
        [12] = {title = 'Posesión de Oxy / Vicodin', class = 'Delito menor', id = 'P.C. 7012', months = 7, fine = 500, color = 'green', description = 'La posesión de oxi/vicodina en pequeña cantidad generalmente para uso personal sin receta'},
        [13] = {title = 'posesión de Oxy / Vicodin', class = 'Delito grave', id = 'P.C. 7013', months = 25, fine = 1500, color = 'red', description = 'La posesión de una cantidad de oxi/vicodina que sea de fabricación'},
        [14] = {title = 'posesión de Oxy/Vicodin con intención de distribuir', class = 'Delito grave', id = 'P.C. 7014', months = 35, fine = 4500, color = 'orange', description = 'La posesión de una cantidad de oxi/vicodina para su distribución'},
        [15] = {title = 'Posesión de éxtasis', class = 'Delito menor', id = 'P.C. 7015', months = 7, fine = 500, color = 'green', description = 'La posesión de éxtasis en pequeñas cantidades generalmente para uso personal'},
        [16] = {title = 'fabricación y posesión de éxtasis', class = 'Delito grave', id = 'P.C. 7016', months = 25, fine = 1500, color = 'red', description = 'La posesión de una cantidad de éxtasis que es de fabricación'},
        [17] = {title = 'Posesión de éxtasis con intención de distribuir', class = 'Delito grave', id = 'P.C. 7017', months = 35, fine = 4500, color = 'orange', description = 'La posesión de una cantidad de éxtasis para su distribución'},
        [18] = {title = 'posesión de opio', class = 'Delito menor', id = 'P.C. 7018', months = 7, fine = 500, color = 'green', description = 'La posesión de opio en pequeña cantidad generalmente para uso personal'},
        [19] = {title = 'fabricación de posesión de opio', class = 'Delito grave', id = 'P.C. 7019', months = 25, fine = 1500, color = 'red', description = 'La posesión de una cantidad de opio que sea de fabricación'},
        [20] = {title = 'Posesión de opio con intención de distribuir', class = 'Delito grave', id = 'P.C. 7020', months = 35, fine = 4500, color = 'orange', description = 'La posesión de una cantidad de opio para su distribución'},
        [21] = {title = 'Posesión de Adderall', class = 'Delito menor', id = 'P.C. 7021', months = 7, fine = 500, color = 'green', description = 'La posesión de adderall en una pequeña cantidad generalmente para uso personal sin receta'},
        [22] = {title = 'fabricación de posesión de Adderall', class = 'Delito grave', id = 'P.C. 7022', months = 25, fine = 1500, color = 'red', description = 'La posesión de una cantidad de adderall que es de fabricación'},
        [23] = {title = 'Posesión de Adderall con intención de distribuir', class = 'Delito grave', id = 'P.C. 7023', months = 35, fine = 4500, color = 'orange', description = 'La posesión de una cantidad de Adderall para su distribución'},
        [24] = {title = 'Delito menor de posesión de Xanax', class = 'Misdemeanor', id = 'P.C. 7024', months = 7, fine = 500, color = 'green', description = 'The possession of xanax in a small quantity usually for personal use without prescription'},
        [25] = {title = 'fabricación de posesión de Xanax', class = 'Delito grave', id = 'P.C. 7025', meses=25, multa=1500, color='red', description = 'La posesión de una cantidad de xanax que sea de fabricación'},
        [26] = {title = 'Posesión de Xanax con intención de distribuir', class = 'Delito grave', id = 'P.C. 7026', months = 35, fine = 4500, color = 'orange', description = 'La posesión de una cantidad de Xanax para su distribución'},
        [27] = {title = 'posesión de hongos', class = 'Delito menor', id = 'P.C. 7027', months = 7, fine = 500, color = 'green', description = 'La posesión de hongos en pequeñas cantidades generalmente para uso personal'},
        [28] = {title = 'fabricación de posesión de hongos', class = 'Delito grave', id = 'P.C. 7028', months = 25, fine = 1500, color = 'red', description = 'La posesión de una cantidad de hongos que es de fabricación'},
        [29] = {title = 'Posesión de hongos con intención de distribuir', class = 'Delito grave', id = 'P.C. 7029', months = 35, fine = 4500, color = 'orange', description = 'La posesión de una cantidad de hongos para su distribución'},
        [30] = {title = 'Posesión de Lean', class = 'Delito menor', id = 'P.C. 7030', months = 7, fine = 500, color = 'green', description = 'La posesión de magro en una pequeña cantidad generalmente para uso personal'},
        [31] = {title = 'fabricación Posesión de Lean', class = 'Delito grave', id = 'P.C. 7031', months = 25, fine = 1500, color = 'red', description = 'La posesión de una cantidad de magro que es de fabricación'},
        [32] = {title = 'Posesión de Lean con intención de distribuir', class = 'Delito grave', id = 'P.C. 7032', months = 35, fine = 4500, color = 'orange', description = 'La posesión de una cantidad de magro para su distribución'},
        [33] = {title = 'Venta de una sustancia controlada', class = 'Delito menor', id = 'P.C. 7033', months = 10, fine = 1000, color = 'green', description = 'La venta de una sustancia que está controlada por la ley'},
        [34] = {title = 'Tráfico de drogas', class = 'Delito grave', id = 'P.C. 7034', months = 0, fine = 0, color = 'red', description = 'El movimiento a gran escala de drogas ilegales'},
        [35] = {title = 'Profanación de un cadáver humano', class = 'Delito grave', id = 'P.C. 7035', months = 20, fine = 1500, color = 'orange', description = 'Cuando alguien daña, perturba o destruye los restos de otra persona'},
        [36] = {title = 'Intoxicación pública', class = 'Infracción', id = 'P.C. 7036', months = 0, fine = 500, color = 'green', description = 'Cuando alguien está intoxicado por encima del límite legal en público'},
        [37] = {title = 'Indecencia pública', class = 'Delito menor', id = 'P.C. 7037', months = 10, fine = 750, color = 'green', description = 'El acto de alguien que se expone de una manera que infringe la moral pública'},
    },
    [8] = {
        [1] = {title = 'Posesión criminal de arma Clase A', class = 'Delito grave', id = 'P.C. 8001', months = 10, fine = 500, color = 'green', description = 'Posesión de arma de fuego Clase A sin licencia'},
        [2] = {title = 'Posesión criminal de arma Clase B', class = 'Delito grave', id = 'P.C. 8002', months = 15, fine = 1000, color = 'green', description = 'Posesión de arma de fuego Clase B sin licencia'},
        [3] = {title = 'Posesión criminal de arma Clase C', class = 'Delito grave', id = 'P.C. 8003', months = 30, fine = 3500, color = 'green', description = 'Posesión de arma de fuego Clase C sin licencia'},
        [4] = {title = 'Posesión criminal de arma Clase D', class = 'Delito grave', id = 'P.C. 8004', months = 25, fine = 1500, color = 'green', description = 'Posesión de arma de fuego Clase D sin licencia'},
        [5] = {title = 'Venta criminal de armas Clase A', class = 'Delito grave', id = 'P.C. 8005', months = 15, fine = 1000, color = 'orange', description = 'El acto de vender un arma de fuego Clase A sin licencia'},
        [6] = {title = 'Venta criminal de armas Clase B', class = 'Delito grave', id = 'P.C. 8006', months = 20, fine = 2000, color = 'orange', description = 'El acto de vender un arma de fuego Clase B sin licencia'},
        [7] = {title = 'Venta criminal de armas Clase C', class = 'Delito grave', id = 'P.C. 8007', months = 35, fine = 7000, color = 'orange', description = 'El acto de vender un arma de fuego Clase C sin licencia'},
        [8] = {title = 'Venta criminal de armas Clase D', class = 'Delito grave', id = 'P.C. 8008', months = 30, fine = 3000, color = 'orange', description = 'El acto de vender un arma de fuego Clase D sin licencia'},
        [9] = {title = 'Uso criminal de arma', class = 'Delito menor', id = 'P.C. 8009', months = 10, fine = 450, color = 'orange', description = 'Uso de un arma en comisión de un delito'},
        [10] = {title = 'Posesión de modificaciones ilegales de armas de fuego', class = 'Delito menor', id = 'P.C. 8010', months = 10, fine = 300, color = 'green', description = 'Estar en posesión de modificaciones de arma de fuego ilegalmente'},
        [11] = {title = 'Tráfico de armas', class = 'Delito grave', id = 'P.C. 8011', months = 0, fine = 0, color = 'red', description = 'El transporte de una gran cantidad de armas de un punto a otro'},
        [12] = {title = 'Blandir un arma', class = 'Delito menor', id = 'P.C. 8012', months = 15, fine = 500, color = 'orange', description = 'El acto de hacer visible un arma de fuego a propósito'},
        [13] = {title = 'Insurrección', class = 'Delito grave', id = 'P.C. 8013', months = 0, fine = 0, color = 'red', description = 'Intento derrocar al gobierno con violencia'},
        [14] = {title = 'Vuelo a espacio aéreo restringido', class = 'Delito grave', id = 'P.C. 8014', months = 20, fine = 1500, color = 'green', description = 'Pilotar una aeronave en un espacio aéreo controlado por el gobierno'},
        [15] = {title = 'Caminando imprudentemente', class = 'Infracción', id = 'P.C. 8015', months = 0, fine = 150, color = 'green', description = 'cruzar una carretera de una manera que sea peligrosa para los vehículos de motor'},
        [16] = {title = 'Uso criminal de explosivos', class = 'Delito grave', id = 'P.C. 8016', months = 30, fine = 2500, color = 'orange', description = 'Uso de explosivos para cometer un delito'},
    },
    [9] = {
        [1] = {title = 'Conducir en estado de ebriedad', class = 'Delito menor', id = 'P.C. 9001', months = 5, fine = 300, color = 'green', description = 'Conducir un vehículo motorizado bajo los efectos del alcohol'},
        [2] = {title = 'Evadir', class = 'Delito menor', id = 'P.C. 9002', months = 5, fine = 400, color = 'green', description = 'Ocultarse o huir de una detención legal'},
        [3] = {title = 'Evasión imprudente', class = 'Delito grave', id = 'P.C. 9003', months = 10, fine = 800, color = 'orange', description = 'Ignorar imprudentemente la seguridad y esconderse o huir de una detención legal mientras '},
        [4] = {title = 'No ceder el paso al vehículo de emergencia', class = 'Infracción', id = 'P.C. 9004', months = 0, fine = 600, color = 'green', description = 'No ceder el paso a los vehículos de emergencia'},
        [5] = {title = 'No obedecer el dispositivo de control de tráfico', class = 'Infracción', id = 'P.C. 9005', months = 0, fine = 150, color = 'green', description = 'No seguir los dispositivos de seguridad de la vía'},
        [6] = {title = 'Vehículo no funcional', class = 'Infracción', id = 'P.C. 9006', months = 0, fine = 75, color = 'green', description = 'Tener un vehículo que ya no funciona en la carretera'},
        [7] = {title = 'Conducción negligente', class = 'Infracción', id = 'P.C. 9007', months = 0, fine = 300, color = 'green', description = 'Conducir de manera que sin saberlo ignore la seguridad'},
        [8] = {title = 'Conducción imprudente', class = 'Delito menor', id = 'P.C. 9008', months = 10, fine = 750, color = 'orange', description = 'Conducir de manera que se ignore deliberadamente la seguridad'},
        [9] = {title = 'Exceso de velocidad en tercer grado', class = 'Infracción', id = 'P.C. 9009', months = 0, fine = 225, color = 'green', description = 'Exceso de velocidad 15 por encima del límite'},
        [10] = {title = 'Exceso de velocidad de segundo grado', class = 'Infracción', id = 'P.C. 9010', months = 0, fine = 450, color = 'green', description = 'Exceso de velocidad 35 por encima del límite'},
        [11] = {title = 'Exceso de velocidad en primer grado', class = 'Infracción', id = 'P.C. 9011', months = 0, fine = 750, color = 'green', description = 'Exceso de velocidad 50 por encima del límite'},
        [12] = {title = 'Operación de vehículo sin licencia', class = 'Infracción', id = 'P.C. 9012', months = 0, fine = 500, color = 'green', description = 'La operación de un vehículo de motor sin la licencia adecuada'},
        [13] = {title = 'Vuelta en U ilegal', class = 'Infracción', id = 'P.C. 9013', months = 0, fine = 75, color = 'green', description = 'Realizar un giro en U donde está prohibido'},
        [14] = {title = 'Paso ilegal', class = 'Infracción', id = 'P.C. 9014', months = 0, fine = 300, color = 'green', description = 'Pasar a otros vehículos de motor de manera prohibida'},
        [15] = {title = 'No mantener el carril', class = 'Infracción', id = 'P.C. 9015', months = 0, fine = 300, color = 'green', description = 'No permanecer en el carril correcto con un vehículo de motor'},
        [16] = {title = 'Giro ilegal', class = 'Infracción', id = 'P.C. 9016', months = 0, fine = 150, color = 'green', description = 'Realizar un giro donde está prohibido'},
        [17] = {title = 'No detenerse', class = 'Infracción', id = 'P.C. 9017', months = 0, fine = 600, color = 'green', description = 'No detenerse ante una parada legal o un dispositivo de tráfico'},
        [18] = {title = 'Estacionamiento no autorizado', class = 'Infracción', id = 'P.C. 9018', months = 0, fine = 300, color = 'green', description = 'Estacionar un vehículo en un lugar que requiere aprobación con cualquiera'},
        [19] = {title = 'Atropello y fuga', class = 'Delito menor', id = 'P.C. 9019', months = 10, fine = 500, color = 'green', description = 'Golpear a otra persona o vehículo y huir del lugar'},
        [20] = {title = 'Conducir sin luces delanteras ni señales', class = 'Infracción', id = 'P.C. 9020', months = 0, fine = 300, color = 'green', description = 'Operar un vehículo sin luces funcionales'},
        [21] = {title = 'Carreras callejeras', class = 'Delito grave', id = 'P.C. 9021', months = 15, fine = 1500, color = 'green', description = 'Operación de vehículos motorizados en un concurso'},
        [22] = {title = 'Piloto sin la licencia adecuada', class = 'Delito grave', id = 'P.C. 9022', months = 20, fine = 1500, color = 'orange', description = 'No estar en posesión de una licencia válida al operar una aeronave'},
        [23] = {title = 'Uso ilegal de un vehículo motorizado', class = 'Delito menor', id = 'P.C. 9023', months = 10, fine = 750, color = 'green', description = 'El uso de un vehículo de motor sin motivo lícito'},
    },
    [10] = {
        [1] = {title = 'Caza en Áreas Restringidas', class = 'Infracción', id = 'P.C. 10001', months = 0, fine = 450, color = 'green', description = 'Cosecha de caza en zonas donde está prohibido hacerlo'},
        [2] = {title = 'Caza sin licencia', class = 'Infracción', id = 'P.C. 10002', months = 0, fine = 450, color = 'green', description = 'Recolección de caza sin la licencia adecuada'},
        [3] = {title = 'Crueldad animal', class = 'Delito menor', id = 'P.C. 10003', months = 10, fine = 450, color = 'green', description = 'El acto de abusar de un animal a sabiendas o no'},
        [4] = {title = 'Caza con un arma que no es de caza', class = 'Delito menor', id = 'P.C. 10004', months = 10, fine = 750, color = 'green', description = 'Usar un arma no declarada o fabricada legalmente para ser utilizada en la recolección de caza silvestre'},
        [5] = {title = 'Caza fuera del horario de caza', class = 'Infracción', id = 'P.C. 10005', months = 0, fine = 750, color = 'green', description = 'Cosechar animales fuera del tiempo especificado para hacerlo'},
        [6] = {title = 'Caza excesiva', class = 'Delito menor', id = 'P.C. 10006', months = 10, fine = 1000, color = 'green', description = 'Tomar más cantidad de juego de la especificada legalmente'},
        [7] = {title = 'Caza furtiva', class = 'Delito grave', id = 'P.C. 10007', months = 20, fine = 1250, color = 'red', description = 'Cosechando un animal que está catalogado como legalmente no cosechable'},
    }
}

Config.AllowedJobs = {}
for index, value in pairs(Config.PoliceJobs) do
    Config.AllowedJobs[index] = value
end
for index, value in pairs(Config.AmbulanceJobs) do
    Config.AllowedJobs[index] = value
end
for index, value in pairs(Config.DojJobs) do
    Config.AllowedJobs[index] = value
end

Config.ColorNames = {
    [0] = "Metallic Black",
    [1] = "Metallic Graphite Black",
    [2] = "Metallic Black Steel",
    [3] = "Metallic Dark Silver",
    [4] = "Metallic Silver",
    [5] = "Metallic Blue Silver",
    [6] = "Metallic Steel Gray",
    [7] = "Metallic Shadow Silver",
    [8] = "Metallic Stone Silver",
    [9] = "Metallic Midnight Silver",
    [10] = "Metallic Gun Metal",
    [11] = "Metallic Anthracite Grey",
    [12] = "Matte Black",
    [13] = "Matte Gray",
    [14] = "Matte Light Grey",
    [15] = "Util Black",
    [16] = "Util Black Poly",
    [17] = "Util Dark silver",
    [18] = "Util Silver",
    [19] = "Util Gun Metal",
    [20] = "Util Shadow Silver",
    [21] = "Worn Black",
    [22] = "Worn Graphite",
    [23] = "Worn Silver Grey",
    [24] = "Worn Silver",
    [25] = "Worn Blue Silver",
    [26] = "Worn Shadow Silver",
    [27] = "Metallic Red",
    [28] = "Metallic Torino Red",
    [29] = "Metallic Formula Red",
    [30] = "Metallic Blaze Red",
    [31] = "Metallic Graceful Red",
    [32] = "Metallic Garnet Red",
    [33] = "Metallic Desert Red",
    [34] = "Metallic Cabernet Red",
    [35] = "Metallic Candy Red",
    [36] = "Metallic Sunrise Orange",
    [37] = "Metallic Classic Gold",
    [38] = "Metallic Orange",
    [39] = "Matte Red",
    [40] = "Matte Dark Red",
    [41] = "Matte Orange",
    [42] = "Matte Yellow",
    [43] = "Util Red",
    [44] = "Util Bright Red",
    [45] = "Util Garnet Red",
    [46] = "Worn Red",
    [47] = "Worn Golden Red",
    [48] = "Worn Dark Red",
    [49] = "Metallic Dark Green",
    [50] = "Metallic Racing Green",
    [51] = "Metallic Sea Green",
    [52] = "Metallic Olive Green",
    [53] = "Metallic Green",
    [54] = "Metallic Gasoline Blue Green",
    [55] = "Matte Lime Green",
    [56] = "Util Dark Green",
    [57] = "Util Green",
    [58] = "Worn Dark Green",
    [59] = "Worn Green",
    [60] = "Worn Sea Wash",
    [61] = "Metallic Midnight Blue",
    [62] = "Metallic Dark Blue",
    [63] = "Metallic Saxony Blue",
    [64] = "Metallic Blue",
    [65] = "Metallic Mariner Blue",
    [66] = "Metallic Harbor Blue",
    [67] = "Metallic Diamond Blue",
    [68] = "Metallic Surf Blue",
    [69] = "Metallic Nautical Blue",
    [70] = "Metallic Bright Blue",
    [71] = "Metallic Purple Blue",
    [72] = "Metallic Spinnaker Blue",
    [73] = "Metallic Ultra Blue",
    [74] = "Metallic Bright Blue",
    [75] = "Util Dark Blue",
    [76] = "Util Midnight Blue",
    [77] = "Util Blue",
    [78] = "Util Sea Foam Blue",
    [79] = "Uil Lightning blue",
    [80] = "Util Maui Blue Poly",
    [81] = "Util Bright Blue",
    [82] = "Matte Dark Blue",
    [83] = "Matte Blue",
    [84] = "Matte Midnight Blue",
    [85] = "Worn Dark blue",
    [86] = "Worn Blue",
    [87] = "Worn Light blue",
    [88] = "Metallic Taxi Yellow",
    [89] = "Metallic Race Yellow",
    [90] = "Metallic Bronze",
    [91] = "Metallic Yellow Bird",
    [92] = "Metallic Lime",
    [93] = "Metallic Champagne",
    [94] = "Metallic Pueblo Beige",
    [95] = "Metallic Dark Ivory",
    [96] = "Metallic Choco Brown",
    [97] = "Metallic Golden Brown",
    [98] = "Metallic Light Brown",
    [99] = "Metallic Straw Beige",
    [100] = "Metallic Moss Brown",
    [101] = "Metallic Biston Brown",
    [102] = "Metallic Beechwood",
    [103] = "Metallic Dark Beechwood",
    [104] = "Metallic Choco Orange",
    [105] = "Metallic Beach Sand",
    [106] = "Metallic Sun Bleeched Sand",
    [107] = "Metallic Cream",
    [108] = "Util Brown",
    [109] = "Util Medium Brown",
    [110] = "Util Light Brown",
    [111] = "Metallic White",
    [112] = "Metallic Frost White",
    [113] = "Worn Honey Beige",
    [114] = "Worn Brown",
    [115] = "Worn Dark Brown",
    [116] = "Worn straw beige",
    [117] = "Brushed Steel",
    [118] = "Brushed Black steel",
    [119] = "Brushed Aluminium",
    [120] = "Chrome",
    [121] = "Worn Off White",
    [122] = "Util Off White",
    [123] = "Worn Orange",
    [124] = "Worn Light Orange",
    [125] = "Metallic Securicor Green",
    [126] = "Worn Taxi Yellow",
    [127] = "police car blue",
    [128] = "Matte Green",
    [129] = "Matte Brown",
    [130] = "Worn Orange",
    [131] = "Matte White",
    [132] = "Worn White",
    [133] = "Worn Olive Army Green",
    [134] = "Pure White",
    [135] = "Hot Pink",
    [136] = "Salmon pink",
    [137] = "Metallic Vermillion Pink",
    [138] = "Orange",
    [139] = "Green",
    [140] = "Blue",
    [141] = "Mettalic Black Blue",
    [142] = "Metallic Black Purple",
    [143] = "Metallic Black Red",
    [144] = "Hunter Green",
    [145] = "Metallic Purple",
    [146] = "Metaillic V Dark Blue",
    [147] = "MODSHOP BLACK1",
    [148] = "Matte Purple",
    [149] = "Matte Dark Purple",
    [150] = "Metallic Lava Red",
    [151] = "Matte Forest Green",
    [152] = "Matte Olive Drab",
    [153] = "Matte Desert Brown",
    [154] = "Matte Desert Tan",
    [155] = "Matte Foilage Green",
    [156] = "DEFAULT ALLOY COLOR",
    [157] = "Epsilon Blue",
    [158] = "Unknown",
}

Config.ColorInformation = {
    [0] = "black",
    [1] = "black",
    [2] = "black",
    [3] = "darksilver",
    [4] = "silver",
    [5] = "bluesilver",
    [6] = "silver",
    [7] = "darksilver",
    [8] = "silver",
    [9] = "bluesilver",
    [10] = "darksilver",
    [11] = "darksilver",
    [12] = "matteblack",
    [13] = "gray",
    [14] = "lightgray",
    [15] = "black",
    [16] = "black",
    [17] = "darksilver",
    [18] = "silver",
    [19] = "utilgunmetal",
    [20] = "silver",
    [21] = "black",
    [22] = "black",
    [23] = "darksilver",
    [24] = "silver",
    [25] = "bluesilver",
    [26] = "darksilver",
    [27] = "red",
    [28] = "torinored",
    [29] = "formulared",
    [30] = "blazered",
    [31] = "gracefulred",
    [32] = "garnetred",
    [33] = "desertred",
    [34] = "cabernetred",
    [35] = "candyred",
    [36] = "orange",
    [37] = "gold",
    [38] = "orange",
    [39] = "red",
    [40] = "mattedarkred",
    [41] = "orange",
    [42] = "matteyellow",
    [43] = "red",
    [44] = "brightred",
    [45] = "garnetred",
    [46] = "red",
    [47] = "red",
    [48] = "darkred",
    [49] = "darkgreen",
    [50] = "racingreen",
    [51] = "seagreen",
    [52] = "olivegreen",
    [53] = "green",
    [54] = "gasolinebluegreen",
    [55] = "mattelimegreen",
    [56] = "darkgreen",
    [57] = "green",
    [58] = "darkgreen",
    [59] = "green",
    [60] = "seawash",
    [61] = "midnightblue",
    [62] = "darkblue",
    [63] = "saxonyblue",
    [64] = "blue",
    [65] = "blue",
    [66] = "blue",
    [67] = "diamondblue",
    [68] = "blue",
    [69] = "blue",
    [70] = "brightblue",
    [71] = "purpleblue",
    [72] = "blue",
    [73] = "ultrablue",
    [74] = "brightblue",
    [75] = "darkblue",
    [76] = "midnightblue",
    [77] = "blue",
    [78] = "blue",
    [79] = "lightningblue",
    [80] = "blue",
    [81] = "brightblue",
    [82] = "mattedarkblue",
    [83] = "matteblue",
    [84] = "matteblue",
    [85] = "darkblue",
    [86] = "blue",
    [87] = "lightningblue",
    [88] = "yellow",
    [89] = "yellow",
    [90] = "bronze",
    [91] = "yellow",
    [92] = "lime",
    [93] = "champagne",
    [94] = "beige",
    [95] = "darkivory",
    [96] = "brown",
    [97] = "brown",
    [98] = "lightbrown",
    [99] = "beige",
    [100] = "brown",
    [101] = "brown",
    [102] = "beechwood",
    [103] = "beechwood",
    [104] = "chocoorange",
    [105] = "yellow",
    [106] = "yellow",
    [107] = "cream",
    [108] = "brown",
    [109] = "brown",
    [110] = "brown",
    [111] = "white",
    [112] = "white",
    [113] = "beige",
    [114] = "brown",
    [115] = "brown",
    [116] = "beige",
    [117] = "steel",
    [118] = "blacksteel",
    [119] = "aluminium",
    [120] = "chrome",
    [121] = "wornwhite",
    [122] = "offwhite",
    [123] = "orange",
    [124] = "lightorange",
    [125] = "green",
    [126] = "yellow",
    [127] = "blue",
    [128] = "green",
    [129] = "brown",
    [130] = "orange",
    [131] = "white",
    [132] = "white",
    [133] = "darkgreen",
    [134] = "white",
    [135] = "pink",
    [136] = "pink",
    [137] = "pink",
    [138] = "orange",
    [139] = "green",
    [140] = "blue",
    [141] = "blackblue",
    [142] = "blackpurple",
    [143] = "blackred",
    [144] = "darkgreen",
    [145] = "purple",
    [146] = "darkblue",
    [147] = "black",
    [148] = "purple",
    [149] = "darkpurple",
    [150] = "red",
    [151] = "darkgreen",
    [152] = "olivedrab",
    [153] = "brown",
    [154] = "tan",
    [155] = "green",
    [156] = "silver",
    [157] = "blue",
    [158] = "black",
}

Config.ClassList = {
    [0] = "Compact",
    [1] = "Sedan",
    [2] = "SUV",
    [3] = "Coupe",
    [4] = "Muscle",
    [5] = "Sport Classic",
    [6] = "Sport",
    [7] = "Super",
    [8] = "Motorbike",
    [9] = "Off-Road",
    [10] = "Industrial",
    [11] = "Utility",
    [12] = "Van",
    [13] = "Bike",
    [14] = "Boat",
    [15] = "Helicopter",
    [16] = "Plane",
    [17] = "Service",
    [18] = "Emergency",
    [19] = "Military",
    [20] = "Commercial",
    [21] = "Train"
}

function GetJobType(job)
	if Config.PoliceJobs[job] then
		return 'police'
	elseif Config.AmbulanceJobs[job] then
		return 'ambulance'
	elseif Config.DojJobs[job] then
		return 'doj'
	else
		return nil
	end
end
