Config = Config or {}
if Config.CustomMechanic then return end
Config.Vehicle = {}
Config.Vehicle.menuCategories = {
    Cosmetics = true,
    Performance = true,
    Paint = true,
    Repair = true,
}


Config.Vehicle.Performance = {
    {label = "Engine Upgrade", id = 11},
    {label = "Brake Upgrade", id = 12},
    {label = "Transmission Upgrade", id = 13},
    {label = "Suspension Upgrade", id = 15},
    {label = "Armour Upgrade", id = 16},
    {label = "Turbo Upgrade", id = 18},
}
Config.Vehicle.Cosmetics = {
    {label = "Spoiler", id = 0},
    {label = "Front Bumper", id = 1},
    {label = "Rear Bumper", id = 2},
    {label = "Side Skirt", id = 3},
    {label = "Exhaust", id = 4},
    {label = "Roll Cage", id = 5},
    {label = "Grille", id = 6},
    {label = "Hood", id = 7},
    {label = "Left Fender", id = 8},
    {label = "Right Fender", id = 9},
    {label = "Roof", id = 10},
    {label = "Vanity Plates", id = 25},
    {label = "Trim A", id = 27},
    {label = "Ornaments", id = 28},
    {label = "Dashboard", id = 29},
    {label = "Dial", id = 30},
    {label = "Door Speaker", id = 31},
    {label = "Seats", id = 32},
    {label = "Steering Wheel", id = 33},
    {label = "Shifter Leaver", id = 34},
    {label = "Plaque", id = 35},
    {label = "Speaker", id = 36},
    {label = "Trunk", id = 37},
    {label = "Hydraulic", id = 38},
    {label = "Engine Block", id = 39},
    {label = "Air Filter", id = 40},
    {label = "Strut", id = 41},
    {label = "Arch Cover", id = 42},
    {label = "Aerial", id = 43},
    {label = "Trim B", id = 44},
    {label = "Fuel Tank", id = 45},
    {label = "Window", id = 46},
    {label = "Livery", id = 48},
    {label = "Horns", id = 14},
    {label = "wheels", id = 'wheels', type = 'menu'},
    {id = 'neon', label = 'Neon', type = 'menu'},
}

Config.Vehicle.WheelMenu = {
    {label = "Custom Tyres", id = -1, wid = 23},
    {label = "Tyre Smoke", id = 20, wid = 23},
    {label = "Sport", id = 0, wid = 23},
    {label = "Muscle", id = 1, wid = 23},
    {label = "Lowrider", id = 2, wid = 23},
    {label = "SUV", id = 3, wid = 23},
    {label = "Offroad", id = 4, wid = 23},
    {label = "Tuner", id = 5, wid = 23},
    {label = "Motorcycle", id = 6, wid = 23},
    {label = "Highend", id = 7, wid = 23},
    {label = "BennysWheel", id = 8, wid = 23},
    {label = "BespokeWheel", id = 9, wid = 23},
    {label = "Dragster", id = 10, wid = 23},
    {label = "Street", id = 11, wid = 23},
    {label = "Rally", id = 12, wid = 23},
}


-- COLORS
Config.Vehicle.ColorType = {
    {label = "Classic", id = 0},
    {label = "Metallic", id = 1},
    {label = "Matte", id = 3},
    {label = "Metal", id = 4},
    {label = "Chrome", id = 5},
}

Config.Vehicle.ColorsIndex = {
    {label = "Chrome", id = 120},
    {label = "Black", id = 0},
    {label = "Carbon Black", id = 147},
    {label = "Graphite", id = 1},
    {label = "Anhracite Black", id = 11},
    {label = "Black Steel", id = 2},
    {label = "Dark Steel", id = 3},
    {label = "Silver", id = 4},
    {label = "Bluish Silver", id = 5},
    {label = "Rolled Steel", id = 6},
    {label = "Shadow Silver", id = 7},
    {label = "Stone Silver", id = 8},
    {label = "Midnight Silver", id = 9},
    {label = "Cast Iron Silver", id = 10},
    {label = "Red", id = 27},
    {label = "Torino Red", id = 28},
    {label = "Formula Red", id = 29},
    {label = "Lava Red", id = 150},
    {label = "Blaze Red", id = 30},
    {label = "Grace Red", id = 31},
    {label = "Garnet Red", id = 32},
    {label = "Sunset Red", id = 33},
    {label = "Cabernet Red", id = 34},
    {label = "Wine Red", id = 143},
    {label = "Candy Red", id = 35},
    {label = "Hot Pink", id = 135},
    {label = "Pfsiter Pink", id = 137},
    {label = "Salmon Pink", id = 136},
    {label = "Sunrise Orange", id = 36},
    {label = "Orange", id = 38},
    {label = "Bright Orange", id = 138},
    {label = "Gold", id = 99},
    {label = "Bronze", id = 90},
    {label = "Yellow", id = 88},
    {label = "Race Yellow", id = 89},
    {label = "Dew Yellow", id = 91},
    {label = "Dark Green", id = 49},
    {label = "Racing Green", id = 50},
    {label = "Sea Green", id = 51},
    {label = "Olive Green", id = 52},
    {label = "Bright Green", id = 53},
    {label = "Gasoline Green", id = 54},
    {label = "Lime Green", id = 92},
    {label = "Midnight Blue", id = 141},
    {label = "Galaxy Blue", id = 61},
    {label = "Dark Blue", id = 62},
    {label = "Saxon Blue", id = 63},
    {label = "Blue", id = 64},
    {label = "Mariner Blue", id = 65},
    {label = "Harbor Blue", id = 66},
    {label = "Diamond Blue", id = 67},
    {label = "Surf Blue", id = 68},
    {label = "Nautical Blue", id = 69},
    {label = "Racing Blue", id = 73},
    {label = "Ultra Blue", id = 70},
    {label = "Light Blue", id = 74},
    {label = "Chocolate Brown", id = 96},
    {label = "Bison Brown", id = 101},
    {label = "Creeen Brown", id = 95},
    {label = "Feltzer Brown", id = 94},
    {label = "Maple Brown", id = 97},
    {label = "Beechwood Brown", id = 103},
    {label = "Sienna Brown", id = 104},
    {label = "Saddle Brown", id = 98},
    {label = "Moss Brown", id = 100},
    {label = "Woodbeech Brown", id = 102},
    {label = "Straw Brown", id = 99},
    {label = "Sandy Brown", id = 105},
    {label = "Bleached Brown", id = 106},
    {label = "Schafter Purple", id = 71},
    {label = "Spinnaker Purple", id = 72},
    {label = "Midnight Purple", id = 142},
    {label = "Bright Purple", id = 145},
    {label = "Cream", id = 107},
    {label = "Ice White", id = 111},
    {label = "Frost White", id = 112},
    {label = "Matte Black", id = 12},
    {label = "Matte Gray", id = 13},
    {label = "Matte Light Gray", id = 14},
    {label = "Matte Ice White", id = 131},
    {label = "Matte Blue", id = 83},
    {label = "Matte Dark Blue", id = 82},
    {label = "Matte Midnight Blue", id = 84},
    {label = "Matte Midnight Purple", id = 149},
    {label = "Matte Schafter Purple", id = 148},
    {label = "Matte Red", id = 39},
    {label = "Matte Dark Red", id = 40},
    {label = "Matte Orange", id = 41},
    {label = "Matte Yellow", id = 42},
    {label = "Matte Lime Green", id = 55},
    {label = "Matte Green", id = 128},
    {label = "Matte Forest Green", id = 151},
    {label = "Matte Foliage Green", id = 155},
    {label = "Matte Olive Darb", id = 152},
    {label = "Matte Dark Earth", id = 153},
    {label = "Matte Desert Tan", id = 154},
    {label = "Brushed Steel", id = 117},
    {label = "Brushed Black Steel", id = 118},
    {label = "Brushed Aluminum", id = 119},
    {label = "Pure Gold", id = 158},
    {label = "Brushed Gold", id = 159},
}

-- WINDOW TINTS

Config.Vehicle.WindowTint = {
    {label = "None", id = 0},
    {label = "Pure Black", id = 1},
    {label = "Darksmoke", id = 2},
    {label = "Lightsmoke", id = 3},
    {label = "Green", id = 4},

}
